# -*- coding: utf-8 -*-
"""arabic character and digits recognition5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LwaD8M9xoPEr_hGRFVjaKEqsWVvP4Ope
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Qio4YxvcULk3aLCVTwIC")
project = rf.workspace("custom-yolov5-ksf4y").project("arabic-characters-recognition")
dataset = project.version(8).download("yolov5")

os.environ["DATASET_DIRECTORY"] = "/content/dataset"

!python train.py --img 416 --batch 16 --epochs 100 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache

from google.colab import files

# Specify the file path
file_path = '/content/yolov5/runs/train/exp/weights/best.pt'

# Download the file
files.download(file_path)

# !python train.py --img 416 --batch 16 --epochs 50 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache



