# -*- coding: utf-8 -*-
"""car plate recognition test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QTSVCxHujnR8cJr-9bVpLaPeFLdzUUY
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

import cv2
import torch

model = torch.hub.load('.', 'custom', path='/content/best.pt', source='local')

images = '/content/images/'

for img in os.listdir(images):
    try:
        img_path = os.path.join(images, img)
        result = model(img_path)
        crops = result.crop(save=True)
    except (OSError, cv2.error) as e:
        print(f"Error processing image {img}: {e}")
        continue

model = torch.hub.load('.', 'custom', path='/content/best.pt', source='local')
# Image
images = '/content/images/'
# Inference
for img in os.listdir(images):
    # check if the image ends with png
    results = model(images + img)
    results.show()